'use client';

import { useMemo, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, BarChart3, Bell, BookOpen, Brush, Cable, Check, ChevronRight, CircleHelp, Crosshair, Database, GitBranch, Info, LayoutGrid, LineChart, ListChecks, Lock, MousePointer2, Play, Radar, Ruler, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Star, Target, Type, Volume2, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@market/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@market/components/ui/tabs';

const toolGroups=[
 {category:'Navigation',tools:[['Symbol search','Change the instrument. Production mode resolves symbols through the Datafeed API.'],['Timeframe','Changes bar aggregation: 1m, 5m, 15m, 1H, 4H, 1D or 1W.'],['Chart type','Switch candles, bars, line, area, Heikin Ashi, Renko or range.'],['Zoom','Changes how many bars are visible without changing the timeframe.'],['Fullscreen','Expands the analytical workspace and hides surrounding navigation.']]},
 {category:'Drawing tools',tools:[['Cursor','Select, move and inspect existing drawings.'],['Crosshair','Align time and price precisely while inspecting OHLCV values.'],['Trend line','Connect two prices to study direction, support or resistance.'],['Ray','A trend line that continues indefinitely to the right.'],['Fibonacci','Plots retracement or extension ratios between two anchor points.'],['Brush','Draw a free-form visual annotation.'],['Rectangle / Ellipse','Mark zones such as consolidation, supply or demand.'],['Text','Attach a note or thesis directly to the chart.'],['Measure','Calculate price change, percentage, bars and elapsed time.'],['Long / Short position','Visualize entry, stop, target and risk-to-reward.'],['Magnet','Snaps drawing anchors to nearby OHLC values.']]},
 {category:'Indicators',tools:[['SMA / EMA','Moving averages that smooth price and help identify trend direction.'],['RSI','Momentum oscillator from 0–100; context matters more than simple overbought/oversold labels.'],['MACD','Compares two moving averages to evaluate momentum and trend changes.'],['Bollinger Bands','Volatility envelope around a moving average.'],['VWAP','Volume-weighted average price for intraday participation context.'],['Volume Profile','Shows traded activity distributed across price levels. Premium preview uses mock volume.'],['Supertrend','ATR-based directional overlay.'],['Ichimoku Cloud','Multi-line view of trend, momentum and potential support/resistance.'],['Stochastic','Momentum oscillator comparing close to a recent high-low range.'],['ADX','Measures trend strength, not trend direction.'],['Cumulative Delta','Estimated difference between buyer- and seller-initiated activity.']]},
 {category:'Workspace',tools:[['Compare','Adds another instrument as an overlay or synchronized pane.'],['Alert','Monitors a price, indicator, signal or flow condition.'],['Events','Overlays macro, geopolitical, policy, sector and company events at the affected chart time. Filter by global, regional, country, sector or instrument scope.'],['Replay','Reveals historical bars sequentially for practice and validation.'],['Layout','Switches between one, two, four or six synchronized charts.'],['Save','Stores the workspace layout when persistence is connected.'],['Snapshot','Creates a chart image for analysis or advisor content.'],['Undo / Redo','Moves backward or forward through drawing changes.']]},
 {category:'Analysis panels',tools:[['Technicals','Summarizes momentum, trend, volatility and ATR statistics.'],['Event timeline','Shows the sequence, scope, severity and observed market reaction of events plotted on the chart. Co-movement does not prove causation.'],['Volume','Shows trading activity, relative volume and VWAP distance.'],['Order flow','Displays mock bid/ask ladder, delta and volume profile. Not literal capital transfer.'],['Strategy tester','Summarizes mock backtest profit, drawdown, profit factor and Sharpe ratio.'],['Signal history','Tracks prior signal states and subsequent validation outcomes.'],['Watchlist','Monitors selected instruments and opens them for investigation.'],['Signals','Explains weighted evidence behind a LONG, WATCH or NEUTRAL state.'],['News','Combines event intelligence with instrument-relevant mock headlines and impact labels.'],['Data','Shows instrument fundamentals and market statistics.']]},
];
const tour=[
 {title:'Choose an instrument',where:'Top-left symbol selector',body:'Search AAPL, NVDA, BTC/USD, EUR/USD and other mock instruments. The instrument context drives price, signal and market-data panels.'},
 {title:'Set analytical resolution',where:'Top timeframe controls',body:'Use lower intervals for execution detail and higher intervals for structure. Changing timeframe does not change the underlying thesis by itself.'},
 {title:'Choose the right visual form',where:'Chart-type menu',body:'Candles expose OHLC structure; line/area reduce noise; Heikin Ashi smooths trend; Renko and range focus on price movement rather than uniform time.'},
 {title:'Add evidence',where:'Indicators menu',body:'Add a small set of complementary studies. Avoid stacking multiple indicators that measure the same behavior.'},
 {title:'Annotate the thesis',where:'Left drawing toolbar',body:'Mark structure, invalidation, target and risk. Select a tool, then click the chart to place a prototype annotation.'},
 {title:'Explain and validate',where:'Chart events + right intelligence rail',body:'Hover event spots to understand what happened, then use Signals for evidence, News for context, and Data for instrument characteristics.'},
 {title:'Monitor the decision',where:'Alert and Watchlist actions',body:'Create a condition that tells you when the thesis needs attention. The prototype never sends orders to a broker.'},
];

export function ChartHelpCenter(){
 const [open,setOpen]=useState(false); const [query,setQuery]=useState(''); const [tourStep,setTourStep]=useState<number|null>(null);
 const filtered=useMemo(()=>toolGroups.map(g=>({...g,tools:g.tools.filter(([name,desc])=>`${name} ${desc}`.toLowerCase().includes(query.toLowerCase()))})).filter(g=>g.tools.length),[query]);
 return <>
  <button onClick={()=>setOpen(true)} className="chart-tool wide text-cyan-300" title="Chart guidance and tool reference"><CircleHelp/>Guide</button>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[88vh] overflow-hidden border-cyan-400/15 bg-[#0e1621] p-0 sm:max-w-[860px]"><DialogHeader className="border-b border-white/8 px-5 py-4"><div className="flex items-center gap-2"><div className="grid size-9 place-items-center rounded-md bg-cyan-400/10 text-cyan-300"><BookOpen className="size-4"/></div><div><DialogTitle>Marketsyde Chart Guide</DialogTitle><DialogDescription className="mt-1 text-xs">Learn the workspace, understand each tool, and follow repeatable analytical workflows.</DialogDescription></div></div></DialogHeader><Tabs defaultValue="start" className="min-h-0 gap-0"><TabsList variant="line" className="w-full justify-start border-b border-white/8 px-4 py-1"><TabsTrigger value="start" className="flex-none px-3 text-[10px]">Quick start</TabsTrigger><TabsTrigger value="tools" className="flex-none px-3 text-[10px]">Tool reference</TabsTrigger><TabsTrigger value="workflows" className="flex-none px-3 text-[10px]">Tutorials</TabsTrigger><TabsTrigger value="data" className="flex-none px-3 text-[10px]">Data & safety</TabsTrigger><TabsTrigger value="production" className="flex-none px-3 text-[10px]">Production</TabsTrigger></TabsList>
   <TabsContent value="start" className="max-h-[66vh] overflow-y-auto p-5"><div className="grid grid-cols-[1fr_270px] gap-5"><div><p className="label">The 60-second workflow</p><div className="mt-3 space-y-2">{tour.map((s,i)=><div key={s.title} className="flex gap-3 rounded-md border border-white/8 bg-white/[.02] p-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-cyan-400/10 text-[9px] font-semibold text-cyan-300">{i+1}</span><div><b className="text-xs">{s.title}</b><p className="mt-1 text-[10px] leading-relaxed text-slate-500">{s.body}</p></div></div>)}</div></div><aside className="space-y-3"><div className="rounded-lg border border-cyan-400/15 bg-cyan-400/5 p-4"><Sparkles className="size-4 text-cyan-300"/><b className="mt-3 block text-sm">Learn inside the chart</b><p className="mt-2 text-[10px] leading-relaxed text-slate-400">The guided tour points to each area and explains the decision it supports.</p><button onClick={()=>{setOpen(false);setTourStep(0)}} className="primary mt-4 w-full"><Play/>Start guided tour</button></div><Tip title="Start simple">Price structure + volume + one momentum study is often more useful than a crowded chart.</Tip><Tip title="Separate observation from decision">A signal is evidence, not an instruction. Define invalidation and risk before monitoring it.</Tip></aside></div></TabsContent>
   <TabsContent value="tools" className="max-h-[66vh] overflow-y-auto p-5"><div className="sticky top-0 z-10 mb-4 flex items-center gap-2 rounded-md border border-white/10 bg-[#111a26] px-3 py-2"><Search className="size-3.5 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools, indicators and panels…" className="w-full bg-transparent text-xs outline-none placeholder:text-slate-600"/>{query&&<button onClick={()=>setQuery('')}><X className="size-3 text-slate-500"/></button>}</div><div className="space-y-5">{filtered.map(g=><section key={g.category}><p className="label">{g.category}</p><div className="mt-2 grid grid-cols-2 gap-2">{g.tools.map(([name,desc])=><div key={name} className="rounded-md border border-white/8 p-3"><b className="text-[10px] text-slate-200">{name}</b><p className="mt-1 text-[9px] leading-relaxed text-slate-500">{desc}</p></div>)}</div></section>)}{filtered.length===0&&<div className="py-12 text-center text-xs text-slate-500">No matching tool found.</div>}</div></TabsContent>
   <TabsContent value="workflows" className="max-h-[66vh] overflow-y-auto p-5"><div className="grid grid-cols-2 gap-3"><Workflow icon={BarChart3} title="Analyze a trend" steps={['Start on 1D or 4H to identify structure.','Draw the dominant trend and important horizontal levels.','Add SMA/EMA plus volume; use RSI or MACD as secondary evidence.','Define the price that invalidates your interpretation.','Create an alert at the decision level.']}/><Workflow icon={Radar} title="Validate a signal" steps={['Open the Signals panel and read the weighted reasons.','Check whether reasons are independent or duplicative.','Compare signal direction with higher-timeframe structure.','Inspect volume, recent news and instrument risk.','Track the signal; do not treat confidence as probability of profit.']}/><Workflow icon={Bell} title="Create a useful alert" steps={['Choose a condition tied to your thesis.','Prefer confirmed closes for structural levels.','Set frequency to avoid repeated noise.','Include the symbol, timeframe and action required.','Review or retire alerts when the thesis changes.']}/><Workflow icon={Play} title="Replay and test" steps={['Select Replay and move to a historical point.','Hide future bars and write your thesis first.','Advance bars without changing your rules.','Record entry, invalidation and target consistently.','Compare decisions across enough samples before drawing conclusions.']}/></div></TabsContent>
   <TabsContent value="data" className="max-h-[66vh] overflow-y-auto p-5"><div className="grid grid-cols-2 gap-4"><InfoCard icon={Database} title="Mock and delayed demo data" body="Every OHLCV bar, order-book level, headline, signal, flow estimate and backtest result in this prototype is synthetic. It is designed to test UX—not to support live trading."/><InfoCard icon={ShieldCheck} title="No brokerage execution" body="Buttons create local prototype state only. The workspace cannot place, modify or cancel market orders and should not be used for financial decisions."/><InfoCard icon={Activity} title="Actual vs inferred flow" body="Fund flows and documented deposits can be actual flow inputs. Price, market cap, volume, open interest and relative strength are participation proxies—not literal transfers of money."/><InfoCard icon={Target} title="Signal confidence" body="Confidence summarizes model agreement and evidence quality. It is not a guaranteed win rate, future return or personalized recommendation."/></div><div className="mt-4 rounded-lg border border-amber-400/15 bg-amber-400/5 p-4"><b className="text-xs text-amber-300">Production requirement</b><p className="mt-2 text-[10px] leading-relaxed text-slate-400">Show exchange attribution, delayed/real-time status, licensing entitlement and the timestamp of every market-data surface. Prevent unsupported indicators or order-flow views when the source data is unavailable.</p></div></TabsContent>
   <TabsContent value="production" className="max-h-[66vh] overflow-y-auto p-5"><div className="grid grid-cols-[1fr_280px] gap-5"><div><p className="label">TradingView Charting Library handoff</p>{[['1','License and self-host','Obtain authorized library access and deploy the library assets with your application.'],['2','Normalize instruments','Create stable symbol IDs, sessions, time zones, pricescale and exchange metadata.'],['3','Connect history','Implement ascending OHLCV bars with correct timestamps, countBack behavior and no-data responses.'],['4','Connect streaming','Maintain independent subscriptions per symbol and resolution; update only the current bar or append a newer bar.'],['5','Persist workspaces','Connect save/load services for layouts, drawings, indicator templates and preferences.'],['6','Enforce entitlements','Separate delayed, real-time, Level 2, derived and restricted datasets by membership and exchange rights.']].map(x=><div className="mt-3 flex gap-3" key={x[0]}><span className="grid size-7 shrink-0 place-items-center rounded bg-violet-400/10 text-[9px] text-violet-300">{x[0]}</span><div><b className="text-[10px]">{x[1]}</b><p className="mt-1 text-[9px] leading-relaxed text-slate-500">{x[2]}</p></div></div>)}</div><aside><InfoCard icon={Cable} title="Adapter status" body="The prototype already includes the Datafeed lifecycle, widget options, theme overrides, feature flags and a licensed-library loader."/><div className="mt-3 rounded-lg border border-white/8 p-4"><p className="label">Engine selector</p><p className="mt-2 text-[9px] leading-relaxed text-slate-500">Choose TradingView API in the top toolbar to test the handoff state. Without licensed assets, Marketsyde preserves the mock chart and explains what is missing.</p></div></aside></div></TabsContent>
  </Tabs></DialogContent></Dialog>
  {tourStep!==null&&<div className="fixed bottom-5 right-5 z-[80] w-[370px] rounded-lg border border-cyan-400/25 bg-[#0f1924]/98 p-4 shadow-2xl"><div className="flex items-center justify-between"><span className="text-[9px] font-semibold uppercase tracking-wider text-cyan-300">Guided tour · {tourStep+1} of {tour.length}</span><button onClick={()=>setTourStep(null)} className="chart-tool"><X/></button></div><div className="mt-3 flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-md bg-cyan-400/10 text-cyan-300"><ChevronRight className="size-4"/></span><div><b className="text-sm">{tour[tourStep].title}</b><p className="mt-1 text-[9px] font-semibold uppercase tracking-wider text-violet-300">{tour[tourStep].where}</p></div></div><p className="mt-3 text-[10px] leading-relaxed text-slate-400">{tour[tourStep].body}</p><div className="mt-4 flex justify-between"><button disabled={tourStep===0} onClick={()=>setTourStep(Math.max(0,tourStep-1))} className="secondary disabled:opacity-30"><ArrowLeft/>Back</button>{tourStep===tour.length-1?<button onClick={()=>setTourStep(null)} className="primary"><Check/>Finish</button>:<button onClick={()=>setTourStep(tourStep+1)} className="primary">Next<ArrowRight/></button>}</div></div>}
 </>
}

function Tip({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border border-white/8 p-4"><b className="text-[10px]">{title}</b><p className="mt-2 text-[9px] leading-relaxed text-slate-500">{children}</p></div>}
function Workflow({icon:Icon,title,steps}:{icon:React.ElementType;title:string;steps:string[]}){return <div className="rounded-lg border border-white/8 p-4"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded bg-cyan-400/8 text-cyan-300"><Icon className="size-4"/></span><b className="text-xs">{title}</b></div><ol className="mt-4 space-y-2">{steps.map((s,i)=><li key={s} className="flex gap-2 text-[9px] leading-relaxed text-slate-400"><span className="text-cyan-400">{i+1}.</span>{s}</li>)}</ol></div>}
function InfoCard({icon:Icon,title,body}:{icon:React.ElementType;title:string;body:string}){return <div className="rounded-lg border border-white/8 bg-white/[.018] p-4"><Icon className="size-4 text-cyan-300"/><b className="mt-3 block text-xs">{title}</b><p className="mt-2 text-[9px] leading-relaxed text-slate-500">{body}</p></div>}
