'use client';

import { useMemo, useState } from 'react';
import { Activity, AreaChart, BarChart3, Bell, Brush, Camera, ChevronDown, Circle, Crosshair, Eye, GitBranch, Globe2, Grid2X2, Info, LayoutGrid, LineChart, List, Lock, Magnet, Maximize2, MessageCircle, MousePointer2, Newspaper, Pause, Play, Plus, Radio, Redo2, RotateCcw, Ruler, Save, Search, Send, Settings2, SlidersHorizontal, Square, Star, Target, Trash2, TrendingUp, Type, Undo2, X, Zap } from 'lucide-react';
import { Popover, PopoverContent, PopoverTrigger } from '@market/components/ui/popover';
import { Switch } from '@market/components/ui/switch';
import { instruments, mockNews, mockOrderBook, technicalBars } from '@market/data/mock-market';
import type { Instrument } from '@market/types';
import { TradingViewChartHost, type ChartEngine } from './tradingview-chart-host';
import { ChartHelpCenter } from './chart-help-center';
import { can } from '@market/lib/permissions';
import type { Tier } from '@market/types';
import { mockMarketEvents, type MarketEvent } from '@market/data/mock-market-events';
import { EventDetail, EventFilter, EventIntelligenceIntro, EventTimelinePanel, type EventScopeFilter } from './event-intelligence-panel';

type ChartKind='Candles'|'Bars'|'Line'|'Area'|'Heikin Ashi'|'Renko'|'Range';
type Props={tier:Tier;requestEventAccess:()=>void;instrument:Instrument;timeframe:string;setTimeframe:(s:string)=>void;indicators:string[];addIndicator:(s:string)=>void;watchlist:string[];toggleWatch:()=>void;createAlert:()=>void;inspectSignal:()=>void};
const drawingTools=[['Cursor',MousePointer2],['Crosshair',Crosshair],['Trend line',TrendingUp],['Ray',GitBranch],['Fibonacci',SlidersHorizontal],['Brush',Brush],['Rectangle',Square],['Ellipse',Circle],['Text',Type],['Measure',Ruler],['Long position',Target],['Short position',Target],['Magnet',Magnet]] as const;
const studyList=['SMA 20','EMA 50','RSI','MACD','Bollinger Bands','VWAP','Volume Profile','Supertrend','Ichimoku Cloud','Stochastic','ADX','Cumulative Delta'];
const chartKinds:[ChartKind,React.ElementType][]=[['Candles',BarChart3],['Bars',Activity],['Line',LineChart],['Area',AreaChart],['Heikin Ashi',BarChart3],['Renko',Grid2X2],['Range',SlidersHorizontal]];

export function TechnicalChartWorkspace(props:Props){
 const {tier,requestEventAccess,instrument,timeframe,setTimeframe,indicators,addIndicator,watchlist,toggleWatch,createAlert,inspectSignal}=props;
 const [chartKind,setChartKind]=useState<ChartKind>('Candles'); const [activeTool,setActiveTool]=useState('Cursor'); const [rightTab,setRightTab]=useState('Watchlist'); const [bottomTab,setBottomTab]=useState('Technicals'); const [replay,setReplay]=useState(false); const [layout,setLayout]=useState('1'); const [zoom,setZoom]=useState(1); const [grid,setGrid]=useState(true); const [logScale,setLogScale]=useState(false); const [marks,setMarks]=useState(true); const [extended,setExtended]=useState(false); const [fullscreen,setFullscreen]=useState(false); const [annotations,setAnnotations]=useState<string[]>(['Earnings gap','Breakout level']); const [toast,setToast]=useState('');
 const [engine,setEngine]=useState<ChartEngine>('prototype'); const [eventLayer,setEventLayer]=useState(true); const [eventScope,setEventScope]=useState<EventScopeFilter>('ALL'); const [selectedEvent,setSelectedEvent]=useState<MarketEvent|null>(mockMarketEvents[1]);
 const eventsUnlocked=can(tier,'eventIntelligence'); const visibleEvents=useMemo(()=>mockMarketEvents.filter(event=>eventScope==='ALL'||event.scope===eventScope),[eventScope]);
 const shown=Math.max(34,Math.round(78/zoom));
 function flash(s:string){setToast(s);setTimeout(()=>setToast(''),1800)}
 return <div className={fullscreen?'fixed inset-0 z-50 overflow-auto bg-[#080d14] p-3':'-m-2'}>
  <div className="mb-2 flex min-w-0 items-center justify-between gap-3 rounded-md border border-white/8 bg-[#0d141e] px-2 py-1.5">
   <div className="flex min-w-0 items-center gap-1">
    <Popover><PopoverTrigger className="chart-tool wide"><Search/><b>{instrument.symbol}</b><span className="text-slate-500">{instrument.market}</span></PopoverTrigger><PopoverContent align="start" className="w-80 border-white/10 bg-[#111a26]"><div className="flex items-center gap-2 rounded border border-white/10 px-2 py-1.5 text-xs text-slate-500"><Search className="size-3"/>Search mock instruments</div>{instruments.slice(0,7).map(i=><button key={i.symbol} className="flex w-full items-center justify-between rounded px-2 py-2 text-left text-xs hover:bg-white/5"><span><b>{i.symbol}</b><small className="ml-2 text-slate-500">{i.name}</small></span><span className={i.change>=0?'up':'down'}>{i.change>0?'+':''}{i.change}%</span></button>)}</PopoverContent></Popover>
    <div className="mx-1 h-5 w-px bg-white/8"/>
    {['1m','5m','15m','1H','4H','1D','1W'].map(t=><button key={t} onClick={()=>setTimeframe(t)} className={`chart-tool ${timeframe===t?'selected':''}`}>{t}</button>)}
    <Popover><PopoverTrigger className="chart-tool wide"><BarChart3/>{chartKind}<ChevronDown/></PopoverTrigger><PopoverContent align="start" className="w-48 border-white/10 bg-[#111a26]">{chartKinds.map(([k,I])=><button key={k} onClick={()=>setChartKind(k)} className={`chart-menu-row ${chartKind===k?'active':''}`}><I/>{k}{chartKind===k&&<span className="ml-auto size-1.5 rounded-full bg-cyan-300"/>}</button>)}</PopoverContent></Popover>
    <Popover><PopoverTrigger className={`chart-tool wide ${engine==='tradingview'?'selected':''}`}><Radio/>{engine==='prototype'?'Marketsyde Engine':'TradingView API'}<ChevronDown/></PopoverTrigger><PopoverContent align="start" className="w-72 border-white/10 bg-[#111a26]"><div className="label mb-2">Chart rendering engine</div><button onClick={()=>setEngine('prototype')} className={`chart-menu-row ${engine==='prototype'?'active':''}`}><Activity/><span><b className="block">Marketsyde prototype</b><small className="text-[8px] text-slate-500">Built-in mock renderer and interactions</small></span></button><button onClick={()=>setEngine('tradingview')} className={`chart-menu-row ${engine==='tradingview'?'active':''}`}><Radio/><span><b className="block">TradingView Charting Library</b><small className="text-[8px] text-slate-500">Production adapter · licensed assets required</small></span></button><div className="mt-2 rounded border border-cyan-400/15 bg-cyan-400/5 p-2 text-[8px] leading-relaxed text-slate-400">The Datafeed API, widget configuration, theme and feature flags are prepared. Add your self-hosted licensed library to activate it.</div></PopoverContent></Popover>
    <Popover><PopoverTrigger className="chart-tool wide"><Activity/>Indicators</PopoverTrigger><PopoverContent align="start" className="w-80 border-white/10 bg-[#111a26]"><div className="mb-2 flex items-center gap-2 rounded border border-white/10 px-2 py-1.5 text-xs text-slate-500"><Search className="size-3"/>Search 100+ technical studies</div><div className="grid grid-cols-2 gap-1">{studyList.map(i=><button onClick={()=>{addIndicator(i);flash(`${i} added`)}} key={i} className="rounded px-2 py-2 text-left text-[10px] text-slate-300 hover:bg-white/5"><Plus className="mr-1 inline size-3 text-cyan-300"/>{i}{['Volume Profile','Cumulative Delta'].includes(i)&&<Lock className="ml-1 inline size-2.5 text-violet-300"/>}</button>)}</div></PopoverContent></Popover>
    <button onClick={()=>flash('Compare symbol layer opened')} className="chart-tool wide"><Plus/>Compare</button><button onClick={createAlert} className="chart-tool wide"><Bell/>Alert</button><Popover><PopoverTrigger className={`chart-tool wide ${eventLayer?'selected':''}`}><Globe2/>Events <span className="rounded bg-cyan-400/10 px-1 text-[7px] text-cyan-300">{visibleEvents.length}</span></PopoverTrigger><PopoverContent align="start" className="w-[430px] border-white/10 bg-[#111a26]"><div className="flex items-start justify-between"><div><div className="label">Event Intelligence Timeline</div><p className="mt-1 text-[8px] text-slate-500">Macro, geopolitical, policy, sector and company effects</p></div><Switch size="sm" checked={eventLayer} onCheckedChange={setEventLayer}/></div><div className="mt-3"><EventFilter scope={eventScope} setScope={setEventScope} locked={!eventsUnlocked} requestAccess={requestEventAccess}/></div><div className="mt-3 grid grid-cols-3 gap-2"><MiniMetric l="Visible events" v={String(visibleEvents.length)} s="Current scope"/><MiniMetric l="Highest impact" v="5 / 5" s="Geopolitical"/><MiniMetric l="Coverage" v="6 layers" s="Demo sources"/></div>{!eventsUnlocked&&<button onClick={requestEventAccess} className="mt-3 w-full rounded border border-violet-400/25 bg-violet-400/8 py-2 text-[9px] text-violet-300"><Lock className="mr-1 inline size-3"/>Unlock advanced scope filters</button>}</PopoverContent></Popover>
    <button onClick={()=>setReplay(!replay)} className={`chart-tool wide ${replay?'selected':''}`}>{replay?<Pause/>:<Play/>}Replay</button><button onClick={()=>setRightTab('Community')} className="chart-tool wide"><MessageCircle/>Share chart</button>
   </div>
   <div className="flex shrink-0 items-center gap-1"><ChartHelpCenter/><button onClick={()=>flash('Chart image captured in demo')} className="chart-tool" title="Snapshot"><Camera/></button><button className="chart-tool" title="Undo"><Undo2/></button><button className="chart-tool" title="Redo"><Redo2/></button><Popover><PopoverTrigger className="chart-tool wide"><LayoutGrid/>{layout} chart</PopoverTrigger><PopoverContent align="end" className="w-52 border-white/10 bg-[#111a26]"><div className="label mb-2">Workspace layout</div><div className="grid grid-cols-3 gap-2">{['1','2','4','6'].map(n=><button key={n} onClick={()=>{setLayout(n);flash(`${n}-chart layout selected`)}} className={`grid aspect-square place-items-center rounded border text-xs ${layout===n?'border-cyan-400 bg-cyan-400/10 text-cyan-300':'border-white/10'}`}>{n}</button>)}<button className="relative grid aspect-square place-items-center rounded border border-violet-400/20 text-violet-300"><Lock className="size-3"/><span className="absolute bottom-1 text-[7px]">CUSTOM</span></button></div></PopoverContent></Popover><button onClick={()=>flash('Layout saved')} className="chart-tool" title="Save layout"><Save/></button><button onClick={()=>setFullscreen(!fullscreen)} className="chart-tool" title="Fullscreen"><Maximize2/></button></div>
  </div>
  <div className="grid min-h-[705px] grid-cols-[38px_minmax(0,1fr)_286px] gap-2 max-xl:grid-cols-[38px_minmax(0,1fr)]">
   <aside className="panel flex flex-col items-center gap-0.5 py-1.5">{drawingTools.map(([name,I])=><button key={name} title={name} onClick={()=>setActiveTool(name)} className={`chart-side-tool ${activeTool===name?'selected':''}`}><I/></button>)}<div className="my-1 h-px w-5 bg-white/8"/><button className="chart-side-tool" title="Lock drawings"><Lock/></button><button onClick={()=>setAnnotations([])} className="chart-side-tool" title="Remove drawings"><Trash2/></button></aside>
   <div className="min-w-0 space-y-2">
    <div className="panel overflow-hidden">
     <div className="flex items-center justify-between border-b border-white/8 px-3 py-2"><div className="flex items-center gap-3"><div><div className="flex items-center gap-2"><b className="text-sm">{instrument.symbol}</b><span className="text-[9px] text-slate-500">· {timeframe} · NASDAQ · MOCK</span><span className="rounded bg-amber-400/8 px-1.5 py-0.5 text-[8px] text-amber-300">DELAYED DEMO</span></div><div className="mt-1 flex gap-3 font-mono text-[9px]"><span className="text-slate-500">O <b className="text-slate-300">137.82</b></span><span className="text-slate-500">H <b className="text-slate-300">139.46</b></span><span className="text-slate-500">L <b className="text-slate-300">137.21</b></span><span className="text-slate-500">C <b className="text-emerald-300">138.85</b></span><span className="text-emerald-300">+3.42%</span></div></div></div><div className="flex items-center gap-1"><button onClick={()=>setZoom(Math.max(.7,zoom-.15))} className="chart-tool">−</button><span className="w-10 text-center text-[9px] text-slate-500">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(2,zoom+.15))} className="chart-tool">+</button><Popover><PopoverTrigger className="chart-tool"><Settings2/></PopoverTrigger><PopoverContent align="end" className="w-64 border-white/10 bg-[#111a26]"><div className="label mb-2">Chart settings</div><Setting label="Grid lines" value={grid} change={setGrid}/><Setting label="Logarithmic scale" value={logScale} change={setLogScale}/><Setting label="Event marks" value={marks} change={setMarks}/><Setting label="Extended hours" value={extended} change={setExtended}/><div className="mt-3 grid grid-cols-2 gap-2"><button className="secondary">Candle colors</button><button className="secondary">Timezone</button></div></PopoverContent></Popover></div></div>
     <div className="relative h-[430px] min-w-0 bg-[#0b1119]"><TradingViewChartHost engine={engine} symbol={instrument.symbol} resolution={timeframe}><MockChart instrument={instrument} kind={chartKind} bars={technicalBars.slice(-shown)} grid={grid} marks={marks} indicators={indicators} activeTool={activeTool} annotations={annotations} addAnnotation={s=>setAnnotations(x=>[...x,s])} events={eventLayer?visibleEvents:[]} selectedEvent={selectedEvent} onSelectEvent={event=>{if(eventsUnlocked){setSelectedEvent(event);setRightTab('News')}else requestEventAccess()}}/></TradingViewChartHost>{replay&&engine==='prototype'&&<div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-md border border-cyan-400/20 bg-[#101a25]/95 px-3 py-2 shadow-xl"><button className="chart-tool"><RotateCcw/></button><button onClick={()=>setReplay(false)} className="chart-tool selected"><Pause/></button><div className="h-1.5 w-40 overflow-hidden rounded bg-white/10"><div className="h-full w-[72%] bg-cyan-400"/></div><span className="font-mono text-[9px] text-cyan-300">BAR 61 / 84</span></div>}</div>
     <div className="flex min-h-8 items-center gap-1 border-t border-white/8 px-3 py-1">{indicators.map(i=><span key={i} className="inline-flex items-center gap-1 rounded bg-white/[.04] px-2 py-1 text-[8px] text-slate-400"><Eye className="size-2.5"/>{i}<Settings2 className="size-2.5"/><X className="size-2.5"/></span>)}<button className="ml-auto text-[8px] text-slate-600">{activeTool} active · click chart to place</button></div>
    </div>
    <div className="panel overflow-hidden"><div className="flex h-8 items-center border-b border-white/8 px-2">{['Technicals','Event timeline','Volume','Order flow','Strategy tester','Signal history'].map(t=><button key={t} onClick={()=>setBottomTab(t)} className={`bottom-tab ${bottomTab===t?'active':''}`}>{t}{t==='Event timeline'&&<span className="ml-1 text-[7px] text-cyan-300">NEW</span>}{['Order flow','Strategy tester'].includes(t)&&<span className="ml-1 text-[7px] text-violet-300">PRO</span>}</button>)}<button className="ml-auto chart-tool"><Maximize2/></button></div><BottomPanel tab={bottomTab} events={visibleEvents} selectedEvent={selectedEvent} onSelectEvent={event=>eventsUnlocked?setSelectedEvent(event):requestEventAccess()} eventScope={eventScope} setEventScope={setEventScope} eventsLocked={!eventsUnlocked} requestEventAccess={requestEventAccess}/></div>
   </div>
    <aside className="panel overflow-hidden max-xl:hidden"><div className="grid grid-cols-6 border-b border-white/8">{[['Watchlist',List],['Alerts',Bell],['Signals',Zap],['News',Newspaper],['Community',MessageCircle],['Data',Info]].map(([t,I])=><button title={t as string} key={t as string} onClick={()=>setRightTab(t as string)} className={`right-tab ${rightTab===t?'active':''}`}><I className="size-3.5"/></button>)}</div>{rightTab === 'Community' ? <CommunityPanel instrument={instrument} /> : <RightPanel tab={rightTab} instrument={instrument} watchlist={watchlist} toggleWatch={toggleWatch} createAlert={createAlert} inspectSignal={inspectSignal} events={visibleEvents} selectedEvent={selectedEvent} onSelectEvent={event=>eventsUnlocked?setSelectedEvent(event):requestEventAccess()}/>}</aside>
  </div>
  {toast&&<div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-md border border-cyan-400/20 bg-[#12202a] px-4 py-2 text-[10px] text-cyan-300">{toast}</div>}
 </div>
}

function MockChart({instrument,kind,bars,grid,marks,indicators,activeTool,annotations,addAnnotation,events,selectedEvent,onSelectEvent}:{instrument:Instrument;kind:ChartKind;bars:typeof technicalBars;grid:boolean;marks:boolean;indicators:string[];activeTool:string;annotations:string[];addAnnotation:(s:string)=>void;events:MarketEvent[];selectedEvent:MarketEvent|null;onSelectEvent:(event:MarketEvent)=>void}){
 const [hover,setHover]=useState<number|null>(null); const [hoverEvent,setHoverEvent]=useState<MarketEvent|null>(null); const W=1000,H=430,top=24,bottom=62,right=58,left=8; const plotH=H-top-bottom; const offset=instrument.price-bars[bars.length-1].close; const adjusted=bars.map(b=>({...b,open:b.open+offset,high:b.high+offset,low:b.low+offset,close:b.close+offset})); const lo=Math.min(...adjusted.map(b=>b.low))-(logScalePad(kind)); const hi=Math.max(...adjusted.map(b=>b.high))+logScalePad(kind); const y=(v:number)=>top+(hi-v)/(hi-lo)*plotH; const step=(W-right-left)/adjusted.length; const x=(i:number)=>left+i*step+step/2; const closePath=adjusted.map((b,i)=>`${i?'L':'M'} ${x(i)} ${y(b.close)}`).join(' '); const sma=adjusted.map((b,i)=>i<19?null:adjusted.slice(i-19,i+1).reduce((s,v)=>s+v.close,0)/20); const smaPath=sma.map((v,i)=>v==null?'':`${i===19?'M':'L'} ${x(i)} ${y(v)}`).join(' '); const h=hover==null?adjusted.length-1:Math.min(adjusted.length-1,hover); const hb=adjusted[h]; const sourceOffset=technicalBars.length-bars.length;
 return <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" className="size-full select-none" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(adjusted.length-1,Math.floor(((e.clientX-r.left)/r.width*(W-right-left)-left)/step))))}} onMouseLeave={()=>setHover(null)} onClick={()=>activeTool!=='Cursor'&&activeTool!=='Crosshair'&&addAnnotation(`${activeTool} · ${hb.time}`)}>
  <rect width={W} height={H} fill="#0b1119"/>{grid&&<g stroke="#ffffff0b" strokeWidth="1">{[0,1,2,3,4,5].map(i=><line key={`h${i}`} x1={left} x2={W-right} y1={top+i*plotH/5} y2={top+i*plotH/5}/>)}{[0,1,2,3,4,5,6,7,8].map(i=><line key={`v${i}`} y1={top} y2={H-bottom+38} x1={left+i*(W-right-left)/8} x2={left+i*(W-right-left)/8}/>)}</g>}
  {kind==='Area'&&<path d={`${closePath} L ${x(adjusted.length-1)} ${H-bottom} L ${x(0)} ${H-bottom} Z`} fill="#32d3e51c"/>}{['Line','Area'].includes(kind)?<path d={closePath} fill="none" stroke="#32d3e5" strokeWidth="2"/>:<g>{adjusted.map((b,i)=>{const up=b.close>=b.open;const color=up?'#34d399':'#fb7185';const body=Math.max(1.2,Math.abs(y(b.open)-y(b.close)));return <g key={i}>{kind!=='Bars'&&<line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={color} strokeWidth="1"/>}<rect x={x(i)-Math.max(1.2,step*.28)} y={Math.min(y(b.open),y(b.close))} width={Math.max(2.4,step*.56)} height={body} fill={kind==='Heikin Ashi'?`${color}cc`:color} rx={kind==='Range'?2:0}/>{kind==='Bars'&&<><line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={color}/><line x1={x(i)-step*.22} x2={x(i)} y1={y(b.open)} y2={y(b.open)} stroke={color}/><line x1={x(i)} x2={x(i)+step*.22} y1={y(b.close)} y2={y(b.close)} stroke={color}/></>}</g>})}</g>}
  {(indicators.some(i=>i.includes('SMA'))||indicators.includes('Volume'))&&<path d={smaPath} fill="none" stroke="#fbbf24" strokeWidth="1.4"/>}
  {adjusted.map((b,i)=><rect key={`vol${i}`} x={x(i)-step*.25} y={H-bottom+8+(1-b.volume/105)*32} width={Math.max(1.5,step*.5)} height={b.volume/105*32} fill={b.close>=b.open?'#34d39955':'#fb718555'}/>) }
  {[0,1,2,3,4,5].map(i=>{const v=hi-i*(hi-lo)/5;return <g key={`axis${i}`}><text x={W-right+6} y={top+i*plotH/5+3} fill="#64748b" fontSize="9" fontFamily="monospace">{v.toFixed(2)}</text></g>})}
  {[0,Math.floor(adjusted.length/4),Math.floor(adjusted.length/2),Math.floor(adjusted.length*.75),adjusted.length-1].map(i=><text key={`time${i}`} x={x(i)-14} y={H-8} fill="#64748b" fontSize="9" fontFamily="monospace">{adjusted[i].time}</text>)}
  <line x1={left} x2={W-right} y1={y(instrument.price)} y2={y(instrument.price)} stroke="#32d3e566" strokeDasharray="4 4"/><rect x={W-right} y={y(instrument.price)-9} width={right} height={18} fill="#22b8c8"/><text x={W-right+7} y={y(instrument.price)+3} fill="#041015" fontSize="10" fontWeight="700" fontFamily="monospace">{instrument.price.toFixed(2)}</text>
  {marks&&<g><circle cx={x(Math.floor(adjusted.length*.38))} cy={H-bottom+49} r="8" fill="#7c3aed"/><text x={x(Math.floor(adjusted.length*.38))-3} y={H-bottom+52} fill="white" fontSize="9">E</text><circle cx={x(Math.floor(adjusted.length*.72))} cy={H-bottom+49} r="8" fill="#0891b2"/><text x={x(Math.floor(adjusted.length*.72))-3} y={H-bottom+52} fill="white" fontSize="9">D</text></g>}
  <g>{events.map(event=>{const i=event.barIndex-sourceOffset;if(i<0||i>=adjusted.length)return null;const color=event.direction==='RISK-ON'?'#34d399':event.direction==='RISK-OFF'?'#fb7185':'#fbbf24';const selected=selectedEvent?.id===event.id;return <g key={event.id} role="button" tabIndex={0} onMouseEnter={e=>{e.stopPropagation();setHoverEvent(event)}} onMouseLeave={()=>setHoverEvent(null)} onClick={e=>{e.stopPropagation();onSelectEvent(event)}} className="cursor-pointer"><rect x={x(i)-(selected?5:3)} y={top} width={selected?10:6} height={plotH} fill={`${color}${selected?'12':'08'}`}/><line x1={x(i)} x2={x(i)} y1={top} y2={H-bottom+40} stroke={`${color}66`} strokeDasharray="3 4"/><circle cx={x(i)} cy={y(adjusted[i].high)-13} r={selected?8:6} fill="#0b1119" stroke={color} strokeWidth={selected?3:2}/><circle cx={x(i)} cy={y(adjusted[i].high)-13} r="2" fill={color}/></g>})}</g>
  {annotations.length>0&&<g><line x1={x(10)} y1={y(adjusted[10].low)} x2={x(34)} y2={y(adjusted[34].high)} stroke="#a78bfa" strokeWidth="1.2"/><line x1={left} x2={W-right} y1={y(instrument.price-3.4)} y2={y(instrument.price-3.4)} stroke="#fbbf2466" strokeDasharray="7 5"/><text x={x(11)} y={y(adjusted[10].low)-8} fill="#a78bfa" fontSize="9">Trend structure</text></g>}
  {hover!=null&&!hoverEvent&&<g><line x1={x(h)} x2={x(h)} y1={top} y2={H-bottom+38} stroke="#94a3b866" strokeDasharray="3 3"/><line x1={left} x2={W-right} y1={y(hb.close)} y2={y(hb.close)} stroke="#94a3b844" strokeDasharray="3 3"/><g transform={`translate(${Math.min(x(h)+12,W-205)},${top+8})`}><rect width="185" height="64" rx="5" fill="#111a26ee" stroke="#ffffff18"/><text x="10" y="15" fill="#94a3b8" fontSize="9">{hb.time} · MOCK OHLCV</text><text x="10" y="32" fill="#e2e8f0" fontSize="10" fontFamily="monospace">O {hb.open.toFixed(2)}  H {hb.high.toFixed(2)}</text><text x="10" y="47" fill="#e2e8f0" fontSize="10" fontFamily="monospace">L {hb.low.toFixed(2)}  C {hb.close.toFixed(2)}</text><text x="10" y="59" fill="#64748b" fontSize="8">VOL {hb.volume.toFixed(1)}M · Δ {hb.delta.toFixed(0)}</text></g></g>}
  {hoverEvent&&(()=>{const i=hoverEvent.barIndex-sourceOffset;const tx=Math.max(12,Math.min(x(i)+12,W-322));const color=hoverEvent.direction==='RISK-ON'?'#34d399':hoverEvent.direction==='RISK-OFF'?'#fb7185':'#fbbf24';return <g transform={`translate(${tx},${top+9})`}><rect width="300" height="116" rx="7" fill="#111a26f7" stroke={`${color}66`}/><text x="12" y="17" fill={color} fontSize="8" fontWeight="700">{hoverEvent.scope} · {hoverEvent.category} · IMPACT {hoverEvent.severity}/5</text><text x="12" y="37" fill="#f1f5f9" fontSize="10" fontWeight="700">{hoverEvent.title.slice(0,50)}</text><text x="12" y="51" fill="#f1f5f9" fontSize="10" fontWeight="700">{hoverEvent.title.slice(50,96)}</text><text x="12" y="72" fill="#94a3b8" fontSize="8">Observed reaction</text><text x="12" y="88" fill="#e2e8f0" fontSize="9">{hoverEvent.reaction}</text><text x="12" y="106" fill="#64748b" fontSize="8">{hoverEvent.region} · {hoverEvent.confidence}% confidence · Click for details</text></g>})()}
 </svg>
}
function logScalePad(kind:ChartKind){return kind==='Renko'?1.8:1.1}
function Setting({label,value,change}:{label:string;value:boolean;change:(v:boolean)=>void}){return <label className="flex items-center justify-between py-2 text-[10px] text-slate-300">{label}<Switch size="sm" checked={value} onCheckedChange={change}/></label>}
function BottomPanel({tab,events=[],selectedEvent=null,onSelectEvent=()=>{},eventScope='ALL',setEventScope=()=>{},eventsLocked=false,requestEventAccess=()=>{}}:{tab:string;events?:MarketEvent[];selectedEvent?:MarketEvent|null;onSelectEvent?:(event:MarketEvent)=>void;eventScope?:EventScopeFilter;setEventScope?:(scope:EventScopeFilter)=>void;eventsLocked?:boolean;requestEventAccess?:()=>void}){if(tab==='Technicals')return <div className="grid h-32 grid-cols-[1fr_220px] gap-3 p-3"><div className="relative overflow-hidden rounded bg-[#0b1119] px-2"><div className="absolute inset-x-0 top-1/3 border-t border-dashed border-rose-400/20"/><div className="absolute inset-x-0 bottom-1/3 border-t border-dashed border-emerald-400/20"/><svg viewBox="0 0 800 110" className="size-full"><path d={technicalBars.map((b,i)=>`${i?'L':'M'} ${i*9.6} ${98-b.rsi}`).join(' ')} fill="none" stroke="#a78bfa" strokeWidth="2"/></svg><span className="absolute left-2 top-2 text-[8px] text-violet-300">RSI 14 · 54.28</span></div><div className="grid grid-cols-2 gap-2"><MiniMetric l="RSI" v="54.28" s="Neutral"/><MiniMetric l="MACD" v="+1.42" s="Bullish"/><MiniMetric l="ADX" v="27.4" s="Trending"/><MiniMetric l="ATR" v="3.18" s="2.29%"/></div></div>;
 if(tab==='Event timeline')return <EventTimelinePanel events={events} selected={selectedEvent} onSelect={onSelectEvent} scope={eventScope} setScope={setEventScope} locked={eventsLocked} requestAccess={requestEventAccess}/>;
 if(tab==='Volume')return <div className="grid h-32 grid-cols-[1fr_220px] gap-3 p-3"><div className="flex items-end gap-1 rounded bg-[#0b1119] p-3">{technicalBars.slice(-36).map((b,i)=><div key={i} className={`flex-1 ${b.close>=b.open?'bg-emerald-400/40':'bg-rose-400/40'}`} style={{height:`${20+b.volume*.7}%`}}/>)}</div><div className="space-y-2"><MiniMetric l="Relative volume" v="2.18×" s="Top 8%"/><MiniMetric l="VWAP distance" v="+1.64%" s="Above"/></div></div>;
 if(tab==='Order flow')return <div className="grid h-32 grid-cols-3 gap-3 p-3"><div className="rounded bg-[#0b1119] p-2"><div className="label">Bid / ask ladder · mock</div>{mockOrderBook.asks.slice().reverse().map((x,i)=><div key={i} className="flex justify-between text-[9px] text-rose-300"><span>{x[0]}</span><span>{x[1].toLocaleString()}</span></div>)}{mockOrderBook.bids.map((x,i)=><div key={i} className="flex justify-between text-[9px] text-emerald-300"><span>{x[0]}</span><span>{x[1].toLocaleString()}</span></div>)}</div><MiniMetric l="Cumulative delta" v="+18.4K" s="Buyer initiated"/><div className="relative overflow-hidden rounded bg-[#0b1119] p-2"><div className="label">Volume profile</div>{[72,94,61,84,45,67].map((w,i)=><div key={i} className="my-1 h-2 bg-cyan-400/25" style={{width:`${w}%`}}/>)}<span className="badge premium absolute right-2 top-2">PREMIUM</span></div></div>;
 if(tab==='Strategy tester')return <div className="grid h-32 grid-cols-4 gap-3 p-3"><MiniMetric l="Net profit" v="+18.42%" s="Mock backtest"/><MiniMetric l="Profit factor" v="1.68" s="42 trades"/><MiniMetric l="Max drawdown" v="−7.12%" s="Moderate"/><MiniMetric l="Sharpe ratio" v="1.44" s="Estimated"/></div>;
 return <div className="h-32 p-3"><div className="grid grid-cols-3 gap-2">{[['10:35','LONG · 82%','Validated +2.8%'],['Aug 28','WATCH · 64%','Expired +0.4%'],['Aug 22','LONG · 76%','Validated +5.1%']].map(x=><div key={x[0]} className="rounded border border-white/8 p-3 text-[9px]"><span className="text-slate-500">{x[0]}</span><b className="mt-2 block text-emerald-300">{x[1]}</b><span className="mt-1 block text-slate-400">{x[2]}</span></div>)}</div></div>}
function RightPanel({tab,instrument,watchlist,toggleWatch,createAlert,inspectSignal,events,selectedEvent,onSelectEvent}:{tab:string;instrument:Instrument;watchlist:string[];toggleWatch:()=>void;createAlert:()=>void;inspectSignal:()=>void;events:MarketEvent[];selectedEvent:MarketEvent|null;onSelectEvent:(event:MarketEvent)=>void}){if(tab==='Watchlist')return <div><div className="flex items-center justify-between border-b border-white/8 p-2"><b className="text-[10px]">Primary watchlist</b><div className="flex"><button className="chart-tool"><Plus/></button><button className="chart-tool"><Settings2/></button></div></div><div className="grid grid-cols-[1fr_54px_54px] px-3 py-2 text-[8px] uppercase text-slate-600"><span>Symbol</span><span>Last</span><span>Chg</span></div>{instruments.slice(0,9).map(i=><button key={i.symbol} className={`grid w-full grid-cols-[1fr_54px_54px] items-center px-3 py-2 text-left text-[9px] hover:bg-white/[.035] ${i.symbol===instrument.symbol?'border-l-2 border-cyan-400 bg-cyan-400/5':''}`}><span><b>{i.symbol}</b><small className="block text-[7px] text-slate-600">{i.market}</small></span><span className="font-mono">{i.price>999?`${(i.price/1000).toFixed(1)}K`:i.price}</span><span className={i.change>=0?'up':'down'}>{i.change>0?'+':''}{i.change}%</span></button>)}<button onClick={toggleWatch} className="mx-3 mt-3 w-[calc(100%-24px)] rounded border border-white/10 py-2 text-[9px] text-cyan-300"><Star className={`mr-1 inline size-3 ${watchlist.includes(instrument.symbol)?'fill-cyan-300':''}`}/>{watchlist.includes(instrument.symbol)?'Remove from watchlist':'Add current symbol'}</button></div>;
 if(tab==='Alerts')return <div className="p-3"><button onClick={createAlert} className="primary w-full"><Bell/>Create alert on {instrument.symbol}</button>{[['Price crosses 142.00','Active'],['RSI crosses below 40','Active'],['Signal confidence > 80%','Pro']].map(x=><div key={x[0]} className="mt-2 rounded border border-white/8 p-3"><div className="flex justify-between text-[9px]"><b>{x[0]}</b><span className={x[1]==='Active'?'text-emerald-300':'text-violet-300'}>{x[1]}</span></div><p className="sub">Once per bar · App notification</p></div>)}</div>;
 if(tab==='Signals')return <div className="p-3"><div className="rounded border border-emerald-400/15 bg-emerald-400/5 p-3"><div className="flex justify-between"><div><div className="label">Composite signal</div><b className="mt-2 block text-lg text-emerald-300">LONG</b></div><span className="badge positive h-fit">82% confidence</span></div>{[['MACD crossover','+21'],['Volume expansion','+17'],['RSI pullback','+14'],['Flow proxy','+12']].map(x=><div key={x[0]} className="mt-2 flex justify-between text-[9px]"><span className="text-slate-400">{x[0]}</span><b className="text-emerald-300">{x[1]}</b></div>)}<button onClick={inspectSignal} className="mt-3 w-full rounded bg-emerald-400/10 py-2 text-[9px] text-emerald-300">Full signal rationale</button></div></div>;
 if(tab==='News')return <div className="space-y-3 p-3"><EventIntelligenceIntro/>{selectedEvent&&<EventDetail event={selectedEvent}/>}<div><div className="label mb-1">Events on chart</div>{events.filter(event=>event.id!==selectedEvent?.id).map(event=><button key={event.id} onClick={()=>onSelectEvent(event)} className="w-full border-b border-white/8 py-2 text-left"><div className="flex justify-between text-[7px] text-slate-600"><span>{event.time} · {event.scope}</span><span>IMPACT {event.severity}/5</span></div><p className="mt-1 text-[9px] leading-snug text-slate-300">{event.title}</p></button>)}</div><div><div className="label mb-1">Latest headlines</div>{mockNews.slice(0,2).map(n=><div key={n.headline} className="border-b border-white/8 py-2"><div className="flex justify-between text-[7px] text-slate-600"><span>{n.time} · {n.source}</span><span>{n.impact}</span></div><p className="mt-1 text-[9px] leading-snug text-slate-400">{n.headline}</p></div>)}</div></div>;
 return <div className="p-3"><div className="label mb-3">Instrument data · mock</div>{[['Market cap','$3.40T'],['Avg volume','184.2M'],['Relative volume','2.18×'],['52W range','$86.62–152.89'],['Beta','1.66'],['Next earnings','Nov 19'],['Short float','1.12%'],['Sector rank','2 / 68']].map(x=><div key={x[0]} className="flex justify-between border-b border-white/5 py-2 text-[9px]"><span className="text-slate-500">{x[0]}</span><b>{x[1]}</b></div>)}</div>}
function MiniMetric({l,v,s}:{l:string;v:string;s:string}){return <div className="rounded border border-white/8 bg-[#0b1119] p-2"><div className="text-[8px] uppercase tracking-wider text-slate-600">{l}</div><div className="mt-1 font-mono text-xs">{v}</div><div className="mt-1 text-[8px] text-slate-500">{s}</div></div>}

function CommunityPanel({ instrument }: { instrument: Instrument }) {
 const [draft, setDraft] = useState('');
 const [shared, setShared] = useState(false);
 return <div className="space-y-3 p-3"><div className="flex items-center justify-between"><div><div className="label">Community · #{instrument.symbol}:{instrument.name}</div><p className="mt-1 text-[8px] text-slate-500">Chart and news context shared with this discussion.</p></div><MessageCircle className="size-3.5 text-cyan-300" /></div><div className="rounded border border-cyan-400/15 bg-cyan-400/5 p-3"><div className="flex justify-between text-[9px]"><b className="text-slate-200">Community engagement</b><span className="text-cyan-300">6.7M votes</span></div><div className="mt-2 flex items-center gap-2"><span className="text-emerald-300">74%</span><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-rose-400/50"><div className="h-full w-3/4 bg-emerald-400" /></div><span className="text-rose-300">26%</span></div></div><article className="rounded border border-white/8 bg-[#0b1119] p-3"><div className="flex items-center justify-between"><b className="text-[10px] text-slate-200">Daniel_Markson</b><span className="text-[8px] text-slate-600">19h</span></div><p className="mt-2 text-[10px] leading-relaxed text-slate-300">Watching the chart structure and the latest headline together. <span className="text-cyan-300">#{instrument.symbol}</span></p><div className="mt-2 flex justify-between text-[8px] text-slate-500"><span>♡ 104 · 🔥 2 · ↗ 2</span><span>3 replies</span></div></article>{shared && <div className="rounded border border-violet-400/20 bg-violet-400/5 p-2 text-[9px] text-violet-200">Shared chart snapshot and cited news for #{instrument.symbol}:{instrument.name}</div>}<div className="flex gap-2"><input aria-label={`Share chart for ${instrument.symbol}`} value={draft} onChange={event => setDraft(event.target.value)} placeholder={`Add a note about ${instrument.symbol}...`} className="min-w-0 flex-1 rounded border border-white/10 bg-[#0b1119] px-2 py-1.5 text-[9px] text-slate-300 outline-none" /><button onClick={() => { setShared(true); setDraft(''); }} className="rounded bg-cyan-400/15 px-2.5 py-1.5 text-[9px] font-semibold text-cyan-300"><Send className="mr-1 inline size-3" />Share</button></div></div>;
}
